#new Sample(/data2/sequencer/A549_GeCKO_Anupama_NextSeq1_expS)
# with Control(/data2/sequencer/A549_GeCKO_Anupama_NextSeq4)

python GeckLib.py /data2/sequencer/A549_GeCKO_Anupama_NextSeq2_rerun/demux/unconcat/Human_GeCKOv2_Library_A_3_mageck.txt ../BarCode1.fastq /data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode1.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode2.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode3.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode4.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode5.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode6.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode7.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode8.fastq 1A_CAll 

python GeckLib.py /data2/sequencer/A549_GeCKO_Anupama_NextSeq2_rerun/demux/unconcat/Human_GeCKOv2_Library_A_3_mageck.txt ../BarCode2.fastq /data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode1.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode2.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode3.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode4.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode5.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode6.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode7.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode8.fastq 2A_CAll

python GeckLib.py /data2/sequencer/A549_GeCKO_Anupama_NextSeq2_rerun/demux/unconcat/Human_GeCKOv2_Library_A_3_mageck.txt ../BarCode3.fastq /data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode1.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode2.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode3.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode4.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode5.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode6.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode7.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode8.fastq 3A_CAll

python GeckLib.py /data2/sequencer/A549_GeCKO_Anupama_NextSeq2_rerun/demux/unconcat/Human_GeCKOv2_Library_A_3_mageck.txt ../BarCode4.fastq /data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode1.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode2.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode3.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode4.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode5.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode6.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode7.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode8.fastq 4A_CAll

python GeckLib.py /data2/sequencer/A549_GeCKO_Anupama_NextSeq2_rerun/demux/unconcat/Human_GeCKOv2_Library_A_3_mageck.txt ../BarCode5.fastq /data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode1.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode2.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode3.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode4.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode5.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode6.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode7.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode8.fastq 5A_CAll 

python GeckLib.py /data2/sequencer/A549_GeCKO_Anupama_NextSeq2_rerun/demux/unconcat/Human_GeCKOv2_Library_A_3_mageck.txt ../BarCode6.fastq /data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode1.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode2.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode3.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode4.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode5.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode6.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode7.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode8.fastq 6A_CAll 

python GeckLib.py /data2/sequencer/A549_GeCKO_Anupama_NextSeq2_rerun/demux/unconcat/Human_GeCKOv2_Library_A_3_mageck.txt ../BarCode7.fastq /data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode1.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode2.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode3.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode4.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode5.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode6.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode7.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode8.fastq 7A_CAll 

python GeckLib.py /data2/sequencer/A549_GeCKO_Anupama_NextSeq2_rerun/demux/unconcat/Human_GeCKOv2_Library_A_3_mageck.txt ../BarCode8.fastq /data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode1.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode2.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode3.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode4.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode5.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode6.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode7.fastq,/data2/sequencer/A549_GeCKO_Anupama_NextSeq4/demux/unconcat/BarCode8.fastq 8A_CAll 

